/*
* generated by Xtext
*/
package animationParser;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return animationParser.ui.internal.MyDslActivator.getInstance().getInjector("animationParser.MyDsl");
	}
	
}
