/**
 *
 * $Id$
 */
package OurPNVis.validation;

import animations.Sequence;

/**
 * A sample validator interface for {@link OurPNVis.Activities}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivitiesValidator {
	boolean validate();

	boolean validateStructure(Sequence value);
}
