/**
 *
 * $Id$
 */
package OurPNVis.validation;

import OurPNVis.Activities;
import OurPNVis.CanChange;
import OurPNVis.Geometry;
import OurPNVis.Shape;
import OurPNVis.Tokens;

/**
 * A sample validator interface for {@link OurPNVis.Place}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PlaceValidator {
	boolean validate();

	boolean validateTokens(Tokens value);
	boolean validateCanchange(CanChange value);
	boolean validateShape(Shape value);
	boolean validateActivities(Activities value);
	boolean validateGeo(Geometry value);
}
