/**
 *
 * $Id$
 */
package OurPNVis.validation;

import OurPNVis.Finished;
import OurPNVis.KeepAnim;
import OurPNVis.ident;

/**
 * A sample validator interface for {@link OurPNVis.Arc}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArcValidator {
	boolean validate();

	boolean validateFinished(Finished value);
	boolean validateKeepanm(KeepAnim value);
	boolean validateIdnt(ident value);
}
