/*
 * generated by Xtext
 */
package animationParser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends animationParser.AbstractMyDslRuntimeModule {

}
