/**
 * generated by Xtext
 */
package animationParser.serializer;

import animationParser.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
