/**
 * generated by Xtext
 */
package animationParser.serializer;

import animationParser.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
