/**
 * generated by Xtext
 */
package animationParser.ui.contentassist;

import animationParser.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
